apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "challenge.name" . }}
  labels:
    {{- include "challenge.labels" . | nindent 4 }}  
data:
  rpc_url: {{ .Values.challenge.rpcUrl | quote }}
  accounts: {{ .Values.challenge.accounts | nospace | b64enc | quote }}
